language: php

matrix:
  fast_finish: true
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: hhvm
  allow_failures:
    - php: hhvm

branches:
  only:
    - master
    - develop

before_script:
  - curl -s https://getcomposer.org/installer | php
  - $(which php) composer.phar --dev install

script:
  - vendor/bin/phpunit
